[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auroboros"
version = "0.1.0"
dependencies = ["pygame"]
requires-python = ">=3.10.8"

[tool.hatch.build]
# exclude = ["as"]
